//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso fortemente tipados, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // classe através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str ou recompile o projeto do Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFile() {
        }
        
        /// <summary>
        ///   Retorna a instância cacheada de ResourceManager utilizada por esta classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceFile", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas
        ///   as pesquisas de recursos que usam esta classe de recursos fortemente tipados.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a attachment; filename=.
        /// </summary>
        internal static string attachmentFilename {
            get {
                return ResourceManager.GetString("attachmentFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Limpa.
        /// </summary>
        internal static string btn_limpa {
            get {
                return ResourceManager.GetString("btn_limpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Vai.
        /// </summary>
        internal static string btn_Vai {
            get {
                return ResourceManager.GetString("btn_Vai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Content-Disposition.
        /// </summary>
        internal static string contentDisposition {
            get {
                return ResourceManager.GetString("contentDisposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Content-Length.
        /// </summary>
        internal static string contentLength {
            get {
                return ResourceManager.GetString("contentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a text/csv.
        /// </summary>
        internal static string contentTypeCsv {
            get {
                return ResourceManager.GetString("contentTypeCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a application/vnd.ms-excel.
        /// </summary>
        internal static string contentTypeExcel {
            get {
                return ResourceManager.GetString("contentTypeExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a text/plain.
        /// </summary>
        internal static string contentTypeTxt {
            get {
                return ResourceManager.GetString("contentTypeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a .csv.
        /// </summary>
        internal static string csv {
            get {
                return ResourceManager.GetString("csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a .dat.
        /// </summary>
        internal static string dat {
            get {
                return ResourceManager.GetString("dat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a ;.
        /// </summary>
        internal static string delimPontoVirgula {
            get {
                return ResourceManager.GetString("delimPontoVirgula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a ,.
        /// </summary>
        internal static string delimVirgula {
            get {
                return ResourceManager.GetString("delimVirgula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a QuerYourFile.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Tem cabecalho?.
        /// </summary>
        internal static string lbl_cabecalho {
            get {
                return ResourceManager.GetString("lbl_cabecalho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Delimitador.
        /// </summary>
        internal static string lbl_Delimitador {
            get {
                return ResourceManager.GetString("lbl_Delimitador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Tipo do arquivo.
        /// </summary>
        internal static string lbl_TipoSaida {
            get {
                return ResourceManager.GetString("lbl_TipoSaida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Arquivo Entrada:.
        /// </summary>
        internal static string leg_ArquivoEntrada {
            get {
                return ResourceManager.GetString("leg_ArquivoEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Arquivo Saída:.
        /// </summary>
        internal static string leg_ArquivoSaida {
            get {
                return ResourceManager.GetString("leg_ArquivoSaida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a csv.
        /// </summary>
        internal static string listCsv {
            get {
                return ResourceManager.GetString("listCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a dat.
        /// </summary>
        internal static string listDat {
            get {
                return ResourceManager.GetString("listDat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a ponto_virgula.
        /// </summary>
        internal static string listPontoVirgula {
            get {
                return ResourceManager.GetString("listPontoVirgula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a tabulacao.
        /// </summary>
        internal static string listTabulacao {
            get {
                return ResourceManager.GetString("listTabulacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a txt.
        /// </summary>
        internal static string listTxt {
            get {
                return ResourceManager.GetString("listTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a virgula.
        /// </summary>
        internal static string listVirgula {
            get {
                return ResourceManager.GetString("listVirgula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a xlsx.
        /// </summary>
        internal static string listXlsx {
            get {
                return ResourceManager.GetString("listXlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a O arquivo foi carregado com sucesso!.
        /// </summary>
        internal static string msgArquivoCarregado {
            get {
                return ResourceManager.GetString("msgArquivoCarregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a O arquivo não foi carregado! Erro:.
        /// </summary>
        internal static string msgArquivoNaoCarregado {
            get {
                return ResourceManager.GetString("msgArquivoNaoCarregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Delimitador especificado inválido!.
        /// </summary>
        internal static string msgDelimitadorInvalido {
            get {
                return ResourceManager.GetString("msgDelimitadorInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Digite uma query válida no editor!.
        /// </summary>
        internal static string msgQueryValida {
            get {
                return ResourceManager.GetString("msgQueryValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Só são aceitos arquivos até 10 MB. Verifique o arquivo!.
        /// </summary>
        internal static string msgTamanhoArquivo {
            get {
                return ResourceManager.GetString("msgTamanhoArquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Não.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Não.
        /// </summary>
        internal static string opt_Nao {
            get {
                return ResourceManager.GetString("opt_Nao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Sim.
        /// </summary>
        internal static string opt_Sim {
            get {
                return ResourceManager.GetString("opt_Sim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a ..
        /// </summary>
        internal static string ponto {
            get {
                return ResourceManager.GetString("ponto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Ponto e vírgula.
        /// </summary>
        internal static string ponto_virgula {
            get {
                return ResourceManager.GetString("ponto_virgula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a EXCEL.
        /// </summary>
        internal static string processoExcel {
            get {
                return ResourceManager.GetString("processoExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a A1.
        /// </summary>
        internal static string rangeExcel {
            get {
                return ResourceManager.GetString("rangeExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a ArquivoLocal.
        /// </summary>
        internal static string sessionArquivoLocal {
            get {
                return ResourceManager.GetString("sessionArquivoLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a ArquivoNome.
        /// </summary>
        internal static string sessionArquivoNome {
            get {
                return ResourceManager.GetString("sessionArquivoNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a ~/UploadDeArquivos/.
        /// </summary>
        internal static string srtUploadArquivo {
            get {
                return ResourceManager.GetString("srtUploadArquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a ~/DownloadDeArquivos/.
        /// </summary>
        internal static string strDownloadArquivo {
            get {
                return ResourceManager.GetString("strDownloadArquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a no.
        /// </summary>
        internal static string stringNo {
            get {
                return ResourceManager.GetString("stringNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Upload.
        /// </summary>
        internal static string stringUpload {
            get {
                return ResourceManager.GetString("stringUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string stringVazia {
            get {
                return ResourceManager.GetString("stringVazia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a yes.
        /// </summary>
        internal static string stringYes {
            get {
                return ResourceManager.GetString("stringYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Tabulação.
        /// </summary>
        internal static string tabulacao {
            get {
                return ResourceManager.GetString("tabulacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Microsoft Excel -.
        /// </summary>
        internal static string tituloExcel {
            get {
                return ResourceManager.GetString("tituloExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a .txt.
        /// </summary>
        internal static string txt {
            get {
                return ResourceManager.GetString("txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a urlDeConexao.
        /// </summary>
        internal static string urlDeConexao {
            get {
                return ResourceManager.GetString("urlDeConexao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Vírgula.
        /// </summary>
        internal static string virgula {
            get {
                return ResourceManager.GetString("virgula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a .xlsx.
        /// </summary>
        internal static string xlsx {
            get {
                return ResourceManager.GetString("xlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pesquisa uma cadeia de caracteres localizada semelhante a Sim.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
